FROM python:3.9.21-alpine3.21

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD ["rq", "worker", "task_queue", "-u", "redis://redis:6379/0"]

CMD ["python3", "/code/worker.py"]
