FROM python:3.9.21-alpine3.21

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "80"]
